### PR TITLE
File listbox widened, grid size 800x800, center and lay flat 3D viewport

### PR DESCRIPTION
**Pull request by deHarro**
Added a means of centering and laying flat the viewport. (issue #177 )

### CODE REVIEW

**Comment by deHarro** [comment]
Hi @martin2250!
I'm sorry for the unsane changes github seems to see for my changes :(
I swear, I only changed two or three lines for the file listbox width.
Perhaps this is using tabs versus blanks, but I don't know. And I don't know where I should change that and in what direction...
Harald

[edit]
Oh, I see...
I additionally had to change some settings of the viewport. I dragged some of the borders with the mouse to fit my needs, this seems to have changed many lines accordingly. Sorry for that.
[\edit]

**Comment by martin2250** [comment]
Hi Harald,

I haven't taken a close look but the code changes look good to me. Thanks! I hope I have time on the weekend to properly look at everything + merge and also reply to your email (although that seems to be resolved already :) ).
Until then, Cheers!

Martin

**Comment by deHarro** [comment]
Hi Martin,
know, that the first approach on "line width" from last year is outdated. I changed that again with one of the last additions.

Namely those two changes are withdrawn:
- increased the listbox width in order to make long lines readable
- activate horizontal scrollbar in order to make long lines readable

The now chosen implementation is "automatically adapting to the currently displayed line length".

Harald

**Comment by martin2250** [comment]
Hi Harald,

I merged two of your changes, but removed the grid size adjustment again. In my eyes, a fixed size of 800x800 is much too large. If we change that, I want it to be adjustable just like the line thickness so everybody can be happy :)

Also some points if you want to submit more pull requests:
- please don't change the version info. Since it's part of the update process, it should only change when there is a new binary release on GitHub.
- separate things (new button / window scaling / grid size) into different pull requests, that makes it a lot easier to review changes
- still please keep submitting them, I think the changes (including the soon adjustable grid size) are a very good addition to OCP :)

Thank you a lot for staying so active around here :)

Have a good week
Martin

**Comment by deHarro** [comment]
Hi Martin,
I try to remember that separating thing if I ever will pull requests 😅 in the future.
Thanks for integrating the stuff!

Harald

**Pull request merged**
