### PR TITLE
Start and End GCode Settings

### PR DESCRIPTION
**Pull request by eried**
My GCode sender (EASEL Inventables) does not support the original header you have hardcoded (I have to modify it all the time in notepad) so I was thinking on a way to cleanly add a way for users of the X-Carve, I think this solution is pretty clean:

image

It looks like Cura :D

### CODE REVIEW

**Comment by martin2250** [comment]
Hi Erwin,

I like the idea of having user-definable start and end gcode, but all of the commands in the header are important because the gcode could produce different results otherwise. Which commands are not supported by EASEL? And, just asking, why are you using EASEL in addition to OCP and not the inbuilt sender? 

Martin

**Comment by eried** [comment]
Easel complains about the G90:

image

Deleting that file make everything works perfectly. The person who recommended me OpenCNCPilot was also using Easel. First I tried without Easel, but the UI in the old (2015) laptop I use for the CNC is not very usable, I need to collapse and expand the panels trying to make it work and the sending process was not smoth (a lot of warning in the begining, then it was cutting on the air, etc). 

I know it requires some research and learning to figure out exactly what are the labels on the center panel etc but before I need to find a fix for the UI (I was thinking on using some Dockable UI similar to the one in VS to have all the panels repositionable, etc)

PS: Here is the GCODE spec from Easel https://inventables.zendesk.com/hc/en-us/articles/360012642474

I export the .nc from Inventor or Fusion 360, your app warns about a bunch of lines from those, but none is critical and everything works ok if I delete the `C90`. Easel adds some header and footer (basically I think is to set metric and relative? and at the end go back to starting point and retract the tool)

**Comment by eried** [comment]
I think the main problem is that in Easel from knowing absolutly nothing about CNCs and start sending a .nc file, doing all the jogging and Z-probing there is a 0 learning curve. You just basically click next a couple of times and then there is a progress bar on top with pause and rate with a nice preview of what is happening below. Your little app is fantastic and I wish I could avoid Easel but as I said the UI is all crammed to the left side, all the labels on top are kinda confusing (textbox for non editable coordinates?, buttons for non modifiable stuff like Metric?) and the jogging is horrible (no separate Z feed, no easy X/Y distance setting).

All is fixable in a fork or future PR though. I just loved the auto-levelling.

**Comment by martin2250** [comment]
According to your link, everything but the G91.1 is supported by EASEL... maybe it also complains because all these independent commands are in a single line.

I'm still considering wehter or not to merge this PR. One issue I see is that if people use it for anything other than G90 etc, it will potentially duplicate the start and end gcode. Try setting the start gcode to "G0 X10, G0 X0" (line break instead of comma of course) and click "Simplify" a couple of times. The start gcode will get added every time you use an edit function.

What exactly do you mean by "the sending process was not smoth (a lot of warning in the begining, then it was cutting on the air, etc)"? The Warnings when loading a file are normal, but air-cutting is usually operator error.

The oddities in the UI you mentioned are all there for a reason:
* read-only textboxes -> the user can select and copy the coordinates to the clipboard
* buttons -> all these buttons serve a function, eg the "metric" button will switch over to "imperial" when a G20 is issued, pressing it will reset GRBL back to metric.

I pretty much always find myself using the same jogging distance/feed for XY and Z, holding down ctrl for rough positioning and then chasing the last 10ths with the reduced feed rate, so I never saw the need for separate feeds.

That said, I'm open to criticism. If you find a way to make the UI usable on lower-end devices, which still looks good, I'm happy to include it.

**Comment by eried** [comment]
> I'm still considering wehter or not to merge this PR. One issue I see is that if people use it for anything other than G90 etc, it will potentially duplicate the start and end gcode. Try setting the start gcode to "G0 X10, G0 X0" (line break instead of comma of course) and click "Simplify" a couple of times. The start gcode will get added every time you use an edit function.

I understand the concern, but in the other hand it just adds infinite flexibility to the software, similar to Cura. 

image

Of course you could break the GCode generation in Cura too, or crash your 3d printer, but isn't that pure operator error all the time? Same as almost everything else in the app? Maybe a "Restore Start/End GCode" button would alliviate your concern.

> The Warnings when loading a file are normal, but air-cutting is usually operator error.

Yes I understand all that and I am guilty. That is why I added the Easel 0 experience reference. I tried for a while, but all those minor nuisances made me just switch until I put more effort in it.

> The oddities in the UI you mentioned are all there for a reason:

Sure, they will make sense after using them for a while but I do not think they are user friendly. The textboxes look the same as the editable ones (not readonly), the buttons for switching do not look like Switches, there is no clear indications of what they do and require a per-instance try to learn. i.e. Why is "Metric" not a combo? or a visual switch?

I havent ever used wpf so take this with a grain of salt. I am going to spend the week trying to use this fork with Start and End GCode and come up with improvements where possible. Maybe these are already bounded by wpf.

**Comment by eried** [comment]
@firetunes recommended me OCP. Maybe he has some great input. Mostly everything I like in Easel was coded by him

**Pull request closed without merging**
