### PR TITLE
Added new features to UI

### PR DESCRIPTION
**Pull request by Paciente8159**
- added [µCNC](https://github.com/Paciente8159/uCNC) alarm, error and setting codes
- added emergency stop button to UI (larger area then soft reset)
- added Grbl settings export and import buttons

### CODE REVIEW

**Comment by Paciente8159** [comment]
Hi there. Big fan of OpenCNCPilot.
Added a couple of features to the UI and some codes based on my own project.

**Comment by martin2250** [comment]
Hi there,

looks good to me on first glance, apart from the indentation with spaces. I'll have a closer look at the code tomorrow.
edit: sorry, did't have time yet :/

Thanks,
Martin

**Comment by martin2250** [comment]
Hi Joao,

sorry, took a bit longer than anticipated. I have a few issues with the code from this PR as it is:

### Tabs/spaces
should be consistent with the rest of the code, no big deal

### Soft reset / e-stop
`Machine.cs` / `public void Kill()`: what is the purpose of this, on the surface it does the same thing as `SoftReset`.

In general, soft reset is already intended to serve as an e-stop and it is bound to the "Escape" key on the keyboard for this purpose. I think the e-stop button should be removed (important/dangerous functions are all bound to the keyboard, this is also the reason why there are no jogging buttons). It can also be obstructed by the other UI elements, which would add confusion and waste precious seconds in the worst case.

### Settings / error codes from µCNC
µCNC is a very cool project, I've seen it in my recommendations even before this PR! Still, OpenCNCPilot is mostly focused on GRBL, meaning that GRBL (or other derivatives) could claim all these codes for different purposes in the future. I'd love to support µCNC as well, but I think it should be clearly separated from GRBL. I can think of two ways to archive this:
- Use a different range of codes for everything that is not compatible with GRBL, eg. having all additional codes start at 1000. This would, of course, also require changes on µCNC and become messy with different forks of GRBL.
- Have a ComboBox in the settings window to select between the different tables, that way other forks of GRBL could also be supported in the future.

I'm open to other suggestions, of course.

### Settings export / import
This seems like a very useful feature! That said, I'm unhappy with the implementation of the import. The `noupdate` variable is not a very elegant way to solve this. Since GRBL settings are already stored in a gcode-like format, I think you should skip the import button altogether and just use the regular file/run mechanism to import settings.

Cheers,
Martin

**Comment by Paciente8159** [comment]
I'll try to reimplement the whole PR.

The spaces mess might have been caused by me doing the implementations in different versions of Visual Studio.

I will drop-off the E-STOP button. The ESC key shortcut associated with soft reset is not explicit in the interface. In case of panic a big red button is always a non brainer for new users. Consider re-styling the soft reset button and hint the ESC key association.

**EDIT**: I'll try to think of a better solution for the integration of µCNC. The combo box to select the Grbl "flavor" is actually a good solution. This will also benefit other active firmwares like Mega-5X and others.

I totally agree on the lack of elegancy of the `noupdate`. I'll try to re-thing the way it's implemented. The import button is just for a matter of clarity to the user. Export and Import is pretty explicit and the lack of an explicit import button might get confusing for most users.

**EDIT**: After re-reading your comment I'll close this PR. I'll re-commit other PR's per new feature. You will have a cleaner history and more granular control on what to merge or not.

Cheers

**Comment by Paciente8159** [comment]
Resubmit PR per feature.

**Pull request closed without merging**
