### PR TITLE
Added support for Ethernet connection

### PR DESCRIPTION
**Pull request by gonzalocargut**
Support for connecting GRBL via ethernet connection was added, all data flow will be sent over a TCP connection using the Ethernet infrastructure.

### CODE REVIEW

**Comment by martin2250** [comment]
Hi Gonzalo,

thanks for the PR, just wanted to let you know I didn't forget about it. I'll look over everything on the weekend.

Cheers!

**Comment by martin2250** [comment]
Hi,

so I looked over the code and it seems fine. Had to do some cosmetic changes though. I'm fairly new to accepting PRs, so the changes landed at martin2250/OpenCNCPilot:pr/151. If you want me to merge this thread, just copy the last commit to your master. Otherwise I'll merge the new branch I've created from your PR.

Cheers!

**Comment by gonzalocargut** [comment]
I don't know how to make my master copy its commit, so I used yours to transfer the changes, as I checked the github interface it didn't offer to copy the changes. From what I check is as it says, only visual and code order changes.
I'm more of a newbie than you on github...

**Comment by martin2250** [comment]
I can't see the changes in your fork. You can also "allow edits from maintainers". Or if you don't care about this exact pull request being merged, I can just merge my pr/151 branch, then your commits will also be transferred to the main branch.

**Comment by gonzalocargut** [comment]
I have manually copied the changes you make, I have the maintainers editing enabled I must say.

**Pull request merged**
